name: Build pico-mac

on:
  push:
  pull_request:
  release:
    types: [published]
  check_suite:
    types: [rerequested]


jobs:
  bins:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Install ARM GCC
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: '13.2.Rel1'

    - name: get submodules
      run: git submodule update --init --recursive

    - name: get pico-sdk
      run: git clone --depth=1 -b adafruit-fruit-jam https://github.com/adafruit/pico-sdk ../pico-sdk

    - name: build targets
      run: |
          ./fetch-rom-dsk.sh
          ./fruitjam-build.sh -m 4096
          ./fruitjam-build.sh -m 4096 -v
          ./fruitjam-build.sh -m 4096 -o
          ./fruitjam-build.sh -m 4096 -v -o
          ./fruitjam-build.sh -m 400
          ./fruitjam-build.sh -m 400 -v
          ./fruitjam-build.sh -m 400 -o
          ./fruitjam-build.sh -m 400 -v -o
          mkdir uf2s
          cp build*/*.uf2 uf2s/
          mkdir elfs
          cp build*/*.elf elfs/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: uf2 files
        path: uf2s/*

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: elf files
        path: elfs/*

    - name: Create release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: build*/*.uf2
        fail_on_unmatched_files: true
        body: "Select a uf2 from the list below."

